urban_project/board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('', views.advertisement_list, name='advertisement_list'),
    path('advertisement/<int:pk>/', views.advertisement_detail, name='advertisement_detail'),
    path('edit/<int:pk>/', views.edit_advertisement, name='edit_advertisement'),
    path('add/', views.add_advertisement, name='add_advertisement'),

]

urban_project/urban_project/urls.py
from django.contrib import admin
from django.urls import path, include
from board import views as board_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls', namespace='board')),
    path('accounts/logout/', board_views.logout_view, name='logout'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', board_views.home, name='home'),
    path('signup/', board_views.signup, name='signup'),
]

urban_project/board/models.py
from django.db import models
from django.contrib.auth.models import User

class Advertisement(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    advertisement = models.ForeignKey(Advertisement, related_name='comments', on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Comment by {self.author} on {self.advertisement}'

urban_project/board/forms.py
from django import forms
from .models import Advertisement
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class AdvertisementForm(forms.ModelForm):
    class Meta:
        model = Advertisement
        fields = ['title', 'content', 'author']


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2',)

urban_project/board/views.py
from django.shortcuts import render, redirect
from board.models import Advertisement
from board.forms import AdvertisementForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout

def logout_view(request):
    logout(request)
    return redirect('home')

from django.shortcuts import render, redirect
from .forms import SignUpForm
from django.contrib.auth import login, authenticate

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('/board')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})

def home(request):
    return render(request, 'home.html')

def advertisement_list(request):
    advertisements = Advertisement.objects.all()
    return render(request, 'board/advertisement_list.html', {'advertisements': advertisements})

def advertisement_detail(request, pk):
    advertisement = Advertisement.objects.get(pk=pk)
    return render(request, 'board/advertisement_detail.html', {'advertisement': advertisement})

@login_required
def add_advertisement(request):
    if request.method == "POST":
        form = AdvertisementForm(request.POST)
        if form.is_valid():
            advertisement = form.save(commit=False)
            advertisement.author = request.user
            advertisement.save()
            return redirect('board:advertisement_list')
    else:
        form = AdvertisementForm()
    return render(request, 'board/add_advertisement.html', {'form': form})

@login_required
def edit_advertisement(request, pk):
    """Функция POST-запроса для изменния статьи"""
    advertisement = Advertisement.objects.get(pk=pk)
    if request.method == "POST":
        form = AdvertisementForm(request.POST)
        if form.is_valid():
            advertisement.delete()
            advertisement = form.save(commit=False)
            advertisement.author = request.user
            advertisement.save()
            return redirect('board:advertisement_list')
        '''Обработака Post-запроса'''
    else:
        initial_dict = {'title': advertisement.title, 'content': advertisement.content, 'author': advertisement.author}
        form = AdvertisementForm(initial=initial_dict)
        '''Отображение страницы по умолчанию'''
    return render(request, 'board/edit_advertisement.html', {'form': form,
                                                            'advertisement': advertisement})

urban_project/board/templates/board/add_advertisement.html
{% extends 'base.html' %}

{% block content %}
  <h2>Add Advertisement</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
{% endblock %}

urban_project/board/templates/board/advertisement_detail.html
{% extends 'base.html' %}

{% block content %}
<h1>Advertisements</h1>
{% if user.is_authenticated %}
    <a href="{% url 'board:edit_advertisement' pk=advertisement.pk %}"><button>Edit Advertisement</button></a>
{% endif %}

<h1>{{ advertisement.title }}</h1>
<p>{{ advertisement.content }}</p>
{% endblock %}

urban_project/board/templates/board/advertisement_list.html
{% extends 'base.html' %}

{% block content %}
<h1>Advertisements</h1>
{% if user.is_authenticated %}
    <a href="{% url 'board:add_advertisement' %}"><button>Add Advertisement</button></a>
{% endif %}
<ul>
  {% for advertisement in advertisements %}
    <li>
      <a href="{% url 'board:advertisement_detail' pk=advertisement.pk %}">{{ advertisement.title }}</a>
    </li>
  {% endfor %}
</ul>

{% endblock %}

urban_project/board/templates/board/edit_advertisement.html
{% extends 'base.html' %}

{% block content %}
  <h2>Edit Advertisement</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
{% endblock %}

urban_project/board/templates/signup.html
<!-- your_app/templates/signup.html -->
{% extends 'base.html' %}

{% block content %}
<h2>Sign up</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
</form>
{% endblock %}

urban_project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}My Django Project{% endblock %}</title>
    <style>
        .navbar {
            overflow: hidden;
            background-color: #333;
            padding: 14px 16px;
        }
        .navbar a {
            float: left;
            color: #f2f2f2;
            text-align: center;
            padding: 12px;
            text-decoration: none;
            font-size: 17px;
        }
        .navbar a:hover {
            background-color: #ddd;
            color: black;
        }
    </style>
</head>
<body>
    <div class="navbar">
        <a href="{% url 'home' %}">Home</a>
        <a href="{% url 'board:advertisement_list' %}">Board</a>
        {% if user.is_authenticated %}
            <a href="{% url 'logout' %}">Logout</a>
        {% else %}
            <a href="{% url 'login' %}">Login</a>
            <a href="{% url 'signup' %}">Sign Up</a>
        {% endif %}
    </div>

    {% block content %}
    {% endblock %}

</body>
</html>

urban_project/templates/home.html
<!-- templates/home.html -->
{% extends 'base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home Page</title>
</head>
<body>
    <h1>Welcome to Our Site!</h1>
    <p><a href="/board/">Go to the board</a></p>
</body>
</html>